dist: trusty
language: node_js
node_js:
  - "8"
install:
  - npm install -g gatsby-cli@1.1.27
  - npm install
  - gatsby build
  - nohup gatsby serve & > /dev/null &
  - while ! nc -z localhost 9000 </dev/null; do sleep 3; done
script:
  - npm run test:skipsnapshots
  - npm run test:coverage
cache:
  directories:
    - "node_modules"