dist: trusty
language: node_js
node_js:
  - "8"
install:
  - npm install -g gatsby-cli@1.1.27
  - npm install
  - gatsby build
  - nohup gatsby serve & > /dev/null &
  - while ! nc -z localhost 9000 </dev/null; do sleep 3; done
script:
  - npm run test:coveragetravis
after_success:
  - npm run test:coveralls
cache:
  directories:
    - "node_modules"
    - "src/fonts"
    - "src/images"
    - "src/components/boton-arriba/__snapshots__"
    - "src/components/cerrar-boton/__snapshots__"
    - "src/components/mas-boton/__snapshots__"
    - "src/components/material/__snapshots__"
    - "src/components/material-flechas/__snapshots__"
    - "src/components/nice-work/__snapshots__"
    - "src/components/popup-imagen/__snapshots__"
    - "src/components/santacc-google-map/__snapshots__"
    - "src/components/trabajo/__snapshots__"
    - "src/layouts/__snapshots__"
    - "src/pages/404/__snapshots__"
    - "src/pages/aviso-legal/__snapshots__"
    - "src/pages/contacto/__snapshots__"
    - "src/pages/la-agencia/__snapshots__"
    - "src/templates/campana/__snapshots__"
    - "src/templates/trabajos/__snapshots__"
    - "src/__snapshots__"
