dist: trusty
language: node_js
node_js:
  - "8"
install:
  - npm install -g gatsby-cli@1.1.27
  - npm install
  - gatsby develop
  - npm run test:snapshotclean
script: bundle exec gatsby build
cache:
  directories:
    - "node_modules"